document.addEventListener("DOMContentLoaded", function () {
    var button = document.getElementById("getWord");

    button.addEventListener("click", function () {
        const lesson1to4 = [
            "안녕하세요",
            "Hello",
            "안녕히 가세요",
            "Goodbye (to someone leaving)",
            "안녕히 계세요",
            "Goodbye (to someone staying)",
            "만나서 반갑습니다",
            "Nice to meet you",
            "네",
            "yes, I see, okay",
            "아니요",
            "No (formal)",
            "좋아합니다",
            "I like",
            "사랑합니다",
            "I love",
            "싫어합니다",
            "I dislike",
            "스포츠",
            "sports",
            "야구",
            "baseball",
            "축구",
            "football",
            "농구",
            "basketball",
            "배구",
            "volleyball",
            "테니스",
            "tennis",
            "탁구",
            "table tennis",
            "피구",
            "dodge ball",
            "하키",
            "hockey",
            "수영",
            "swimming",
            "골프",
            "golf",
            "등산",
            "hiking",
            "음악",
            "music",
            "시",
            "poetry",
            "댄스",
            "to dance",
            "역사",
            "history",
            "음식",
            "food",
            "고양이",
            "cat",
            "개",
            "dog",
            "원숭이",
            "monkey",
            "벌레",
            "insect",
            "거미",
            "spider",
            "책",
            "book",
            "작가",
            "author",
            "사전",
            "dictionary",
            "영화",
            "movie",
            "김치",
            "kimchi",
            "삼겹살",
            "pork belly",
            "더",
            "more (used before feeling)",
            "덜",
            "less (used before feeling)",
            "원합니다",
            "I want",
            "원하지 않습니다",
            "I don't want",
            "+고 싶습니다",
            "I want to",
            "+고 싶지 않습니다",
            "I don't want to",
            "주세요",
            "Please give me...",
            "하다",
            "to do",
            "먹다",
            "to eat",
            "태어니다",
            "to be born",
            "받다",
            "to get, to receive, to acquire",
            "벌다",
            "to earn (money)",
            "울다",
            "to cry",
            "죽다",
            "to die",
            "웃다",
            "to laugh, smile",
            "게임을 하다",
            "to play game/s",
            "일을 하다",
            "to work",
            "게임",
            "game",
            "하지만",
            "but, however",
            "알바",
            "part-time job",
            "돈",
            "money",
            "일",
            "work",
            "연필",
            "pencil",
            "자동차",
            "car",
            "배",
            "boat",
            "핸드폰",
            "cell phone",
            "사랑",
            "love",
            "힌트",
            "hint",
            "도 (particle)",
            "also, too",
            "만 (particle)",
            "only",
            "야채",
            "vegetable",
            "과일",
            "fruit",
            "바나나",
            "banana",
            "포도",
            "grape",
            "토마토",
            "tomato",
            "레몬",
            "lemon",
            "오렌지",
            "orange",
            "아이스크림",
            "ice cream",
            "차",
            "tea",
            "참치",
            "tuna"
        ];
        const lesson5 = [
            "가다",
            "to go",
            "오다",
            "to come",
            "놀다",
            "to play, to hang out",
            "살다",
            "to live",
            "공부를 하다",
            "to study",
            "좋아하다",
            "to like",
            "싫어하다",
            "to dislike",
            "미워하다",
            "to hate",
            "사랑을 하다",
            "to love",
            "환전을 하다",
            "to exchange money",
            "원하다",
            "to want",
            "공부",
            "study",
            "학교",
            "school",
            "집",
            "home, house",
            "병원",
            "hospital",
            "치과",
            "dentist",
            "수영장",
            "swimming pool",
            "도서관",
            "library",
            "사무실",
            "office",
            "카페",
            "cafe",
            "은행",
            "bank",
            "슈퍼 (마켓)",
            "supermarket",
            "영화관",
            "movie theater",
            "박물관",
            "museum",
            "바다",
            "ocean",
            "바닷가",
            "beach",
            "주소",
            "address",
            "집 주소",
            "home address",
            "고향",
            "hometown",
            "도시",
            "city",
            "지역",
            "An area, region",
            "길",
            "street, road",
            "부분",
            "part, portion",
            "연극",
            "performance (play)",
            "방송",
            "a broadcast",
            "프로그램",
            "program",
            "치즈",
            "cheese",
            "에",
            "to, at, in (particle)",
            "씨",
            "Mr./Mrs./Ms.",
        ];
        const lesson6 = [
            "말을 하다",
            "to speak, say",
            "거짓말을 하다",
            "to lie",
            "이다",
            "to be",
            "있다",
            "to exist",
            "키우다",
            "to raise a pet",
            "진실을 말하다",
            "to tell the truth",
            "말",
            "word",
            "거짓말",
            "lie",
            "진실",
            "truth",
            "의미",
            "meaning",
            "의견",
            "opinion",
            "성격",
            "personality",
            "차이",
            "difference",
            "사이다",
            "soda",
            "아파트",
            "apartment",
            "친구",
            "friend",
            "여자 친구",
            "girlfriend",
            "남자 친구",
            "boyfriend",
            "외국",
            "foreign country",
            "외국어",
            "foreign language",
            "섬",
            "island",
            "정원",
            "garden",
            "호수",
            "lake",
            "강",
            "river",
            "지금",
            "right now",
            "이제",
            "from now",
            "사람",
            "person",
            "신",
            "god",
            "티비",
            "TV",
            "펜",
            "pen",
            "우유",
            "milk",
            "물",
            "water",
            "마시다",
            "to drink",
            "보다",
            "to see",
            "읽다",
            "to read",
            "듣다",
            "to listen",
            "믿다",
            "to believe",
            "신문",
            "newspaper",
            "뉴스",
            "news",
            "지도",
            "map",
            "사진",
            "photo",
            "카메라",
            "camera",
            "사진을 찍다",
            "to take a photo",
            "그림",
            "drawing",
            "그리다",
            "to draw",
            "그림을 그리다",
            "to draw a picture",
            "출발을 하다",
            "to depart",
            "도착을 하다",
            "to arrive",
            "떨어지다",
            "to fall",
            "떨어뜨리다",
            "to drop (something)",
            "열다",
            "to open",
            "닫다",
            "to close",
            "만들다",
            "to make",
        ];
        const lesson7 = [
            "선생님",
            "teacher",
            "학생",
            "student",
            "잘",
            "well",
            "요즘",
            "nowadays",
            "정말",
            "really",
            "파스타",
            "pasta",
            "피자",
            "pizza",
            "초밥",
            "sushi",
            "회",
            "sashimi",
            "수학",
            "math",
            "과학",
            "science",
            "미술",
            "art",
            "숙제",
            "homework",
            "숙제를 하다",
            "to do homework",
            "시험",
            "test",
            "결과",
            "result",
            "무엇",
            "what",
            "가르치다",
            "to teach",
            "배우다",
            "to learn",
            "기다리다",
            "to wait",
            "앉다",
            "to sit",
            "서다",
            "to stand",
            "눕다",
            "to lie down",
            "차다",
            "to kick",
            "치다",
            "to hit",
            "싸우다",
            "to fight",
            "이기다",
            "to win",
            "지다",
            "to lose",
            "잘 지내세요? ",
            "Are you doing well?",
            "안녕히 주무세요",
            "Good night",
            "그릇",
            "bowl",
            "젓가락",
            "chopsticks",
            "포크",
            "fork",
            "가위",
            "scissors",
            "스테이크",
            "steak",
            "감자",
            "potato",
            "양피",
            "onion",
            "햄버거",
            "hamburger",
            "힘",
            "power",
            "자리",
            "seat",
            "동물",
            "animal",
            "꿈을 꾸다",
            "to dream",
            "춤을 추다",
            "to dance",
            "소시지",
            "sausage",
        ];
        const lesson8 = [
            "알겠습니다",
            "understood",
            "언제",
            "when",
            "어디",
            "where",
            "누구",
            "who",
            "왜",
            "why",
            "어떻게",
            "how",
            "잠",
            "sleep",
            "잠을 자다",
            "to sleep",
            "일어나다",
            "to get up",
            "가방",
            "bag",
            "우리",
            "we, us",
            "나라",
            "country",
            "그러면",
            "well then",
            "오늘",
            "today",
            "내일",
            "tomorrow",
            "어제",
            "yesterday",
            "밤",
            "night",
            "교수",
            "professor",
            "의사",
            "doctor",
            "가수",
            "singer",
            "대학교",
            "university",
            "화장실",
            "bathroom",
            "냉장고",
            "refrigerator",
            "냉동실",
            "freezer",
            "침대",
            "bed",
            "침실",
            "bedroom",
            "거실",
            "living room",
            "방",
            "room",
            "문",
            "door",
            "열쇠",
            "key",
            "나가다",
            "to go out",
            "나오다",
            "to come out",
            "걷다",
            "to walk",
            "걸어가다",
            "to go on foot",
            "달리다",
            "to run",
            "뛰다",
            "to run, to jump",
            "밥을 먹다",
            "to eat a meal",
            "밥",
            "rice, meal",
            "빵",
            "bread",
            "버터",
            "butter",
            "캔디",
            "candy",
            "과자",
            "snack",
            "설탕",
            "sugar",
            "소금",
            "salt",
            "후추",
            "pepper",
            "후식",
            "dessert",
            "아침 식사",
            "breakfast",
            "점심 식사",
            "lunch",
            "저녁 식사",
            "dinner",
            "알겠다",
            "to know, to understand",
        ];
        const lesson9 = [
            "죄송합니다",
            "Im sorry",
            "감사하다",
            "to be thankful",
            "웨이터",
            "waiter",
            "식당",
            "restaurant",
            "그리고",
            "and",
            "그래서",
            "so, therefore",
            "볶음밥",
            "fried rice",
            "아주",
            "very",
            "조금",
            "a little",
            "조금만",
            "only a little",
            "많이",
            "a lot",
            "많다",
            "to be many",
            "맛",
            "flavor",
            "춥다",
            "to be cold (weather)",
            "차갑다",
            "to be cold (touch)",
            "덥다",
            "to be hot (weather)",
            "뜨겁다",
            "to be hot (touch)",
            "따뜻하다",
            "to be warm",
            "시원하다",
            "to be cool",
            "맑다",
            "to be clear (weather)",
            "괜찮다",
            "to be okay",
            "악하다",
            "to be evil",
            "맛이 있다",
            "to be delicious",
            "멋이 있다",
            "to be cool, stylish",
            "좋다",
            "to be good",
            "나쁘다",
            "to be bad",
            "예쁘다",
            "to be pretty",
            "아름답다",
            "to be beautiful",
            "크다",
            "to be big",
            "배가 고프다",
            "to be hungry",
            "목이 마르다",
            "to be thirsty",
            "흔하다",
            "to be common",
            "드물다",
            "to be rare",
            "내다",
            "to pay",
            "작다",
            "to be small",
            "수영을 하다",
            "to swim",
            "의자",
            "chair",
            "비싸다",
            "to be expensive",
            "맵다",
            "to be spicy",
            "수프",
            "soup",
            "날씨",
            "weather",
            "비가 오다",
            "to rain",
            "눈이 오다",
            "to snow",
            "술",
            "alcohol",
            "친절하다",
            "to be nice",
            "강하다",
            "to be strong",
            "약하다",
            "to be weak",
        ];
        const lesson10 = [
            "글쎄요",
            "well...",
            "    케이크",
            "cake",
            "것",
            "thing",
            "머리",
            "head, hair",
            "머리카락",
            "hair",
            "털",
            "hair (not on head), fur",
            "몸",
            "body",
            "눈",
            "eye",
            "입",
            "mouth",
            "입술",
            "lips",
            "심장",
            "heart",
            "어깨",
            "shoulder",
            "위",
            "stomach",
            "허리",
            "waist",
            "이빨",
            "teeth",
            "혀",
            "tongue",
            "코",
            "nose",
            "귀",
            "ear",
            "발",
            "foot",
            "발가락",
            "toe",
            "다리",
            "leg",
            "팔",
            "arm",
            "목",
            "neck, throat",
            "소리",
            "sound, noise",
            "목소리",
            "voice",
            "가슴",
            "chest",
            "등",
            "back of body",
            "손",
            "hand",
            "손가락",
            "finger",
            "건강하다",
            "to be healthy",
            "건강",
            "health",
            "아프다",
            "to be sick/hurt",
            "피곤하다",
            "to be tired",
            "졸리다",
            "to be sleepy",
            "쉬다",
            "to rest",
            "바쁘다",
            "to be busy",
            "부엌",
            "kitchen",
            "주방",
            "kitchen",
            "낮다",
            "to be low",
            "높다",
            "to be high",
            "쉽다",
            "to be easy",
            "단순하다",
            "to be simple",
            "어렵다",
            "to be difficult",
            "길다",
            "to be long",
            "멀다",
            "to be far",
            "달다",
            "to be sweet",
            "시다",
            "to be sour",
            "어둡다",
            "to be dark",
            "밝다",
            "to be bright",
            "어떤",
            "what kind of",
            "그런",
            "that kind of",
            "이런",
            "this kind of",
            "짧다",
            "to be short (in length)",
            "생각하다",
            "to think",
            "잘생긴",
            "handsome",
            "재미있다",
            "to be fun, interesting",
            "빠르다",
            "to be fast",
            "느리다",
            "to be slow",
            "싸다",
            "to be cheap",
            "무겁다",
            "to be heavy",
            "가볍다",
            "to be light",
            "중요하다",
            "to be important",
            "새롭다",
            "to be new",
            "귀엽다",
            "to be cute",
            "추하다",
            "to be ugly",
            "깨끗하다",
            "to be clean",
            "더럽다",
            "to be dirty",
            "시험을 보다",
            "to take a test",
            "방법",
            "way, method",
            "잡다",
            "to catch, grab",
            "찾다",
            "to find, look for",
            "컴퓨터",
            "computer",
            "저렴하다",
            "to be inexpensive",
        ];
        const lesson11 = [
            "예를 들면",
            "for example, for instance",
            "색",
            "color",
            "살구",
            "apricot",
            "살구색",
            "apricot color",
            "시간",
            "time",
            "시대",
            "An age,period",
            "티셔츠",
            "t-shirt",
            "이름",
            "name",
            "얼굴",
            "face",
            "턱",
            "chin",
            "뺨",
            "cheek",
            "여드름",
            "pimple, acne",
            "주름",
            "wrinkles",
            "옷",
            "clothes",
            "속옷",
            "underwear",
            "모자",
            "hat",
            "같다",
            "to be the same",
            "비슷하다",
            "to be similar",
            "다르다",
            "to be different",
            "빼다",
            "to remove",
            "추가 하다",
            "to add something",
            "패다",
            "to beat",
            "동그랗다",
            "to be round",
            "희망",
            "hope",
            "국기",
            "flag",
            "무슨",
            "what (adjective)",
            "빨간색",
            "red",
            "노란색",
            "yellow",
            "파란색",
            "blue",
            "초록색",
            "green",
            "하얀색",
            "white",
            "흰색",
            "white",
            "까만색",
            "black",
            "검정색",
            "black",
            "뱀",
            "snake",
            "개구리",
            "frog",
            "이",
            "this",
            "그",
            "that",
            "저",
            "that (over there)",
            "여기",
            "here",
            "거기",
            "there",
            "저기",
            "there (farther away)",
            "요리",
            "cooking",
            "요리하다",
            "to cook",
            "섞다",
            "to mix",
            "공",
            "ball",
            "드레스",
            "dress",
            "건물",
            "building",
            "다리",
            "bridge, leg",
            "단계",
            "step",
            "계단",
            "stairs",
            "무섭다",
            "to be scary, to be scared",
            "곳",
            "place",
            "선물",
            "present",
            "산",
            "mountain",
            "새",
            "bird",
            "말",
            "horse",
            "양",
            "sheep",
            "우산",
            "umbrella",
            "거울",
            "mirror",
            "벽",
            "wall",
            "창문",
            "window",
            "노트북",
            "laptop",
            "신뢰",
            "trust, faith",
            "모니터",
            "monitor",
            "문제",
            "problem",
            "질문",
            "question",
            "질문하다",
            "to ask a question",
            "자르다",
            "to cut off",
            "베다",
            "to cut into",
            "그럼",
            "well then",
        ];
        const lesson12 = [
          "영",
          "0",
          "일",
          "1",
          "이",
          "2",
          "삼",
          "3",
          "사",
          "4",
          "오",
          "5",
          "육",
          "6",
          "칠",
          "7",
          "팔",
          "8",
          "구",
          "9",
          "십",
          "10",
          "백",
          "100",
          "천",
          "1000",
          "만",
          "10,000",
          "기쁘다",
          "to be happy",
          "행복하다",
          "to be happy",
          "슬프다",
          "to be sad",
          "자연스럽다",
          "to be natural",
          "훌륭하다",
          "to be wonderful",
          "결혼",
          "marriage",
          "결혼하다",
          "to marry",
          "무례하다",
          "to be rude",
          "예의가 바르다",
          "to be polite",
          "가격",
          "price, cost",
          "손님",
          "guest, customer",
          "이웃",
          "neighbor",
          "번호",
          "number (ID, phone number)",
          "전화",
          "phone call",
          "전화번호",
          "phone number",
          "전화하다",
          "to call",
          "전화를 받다",
          "to answer the phone",
          "직원",
          "employee",
          "회사",
          "company",
          "사장님",
          "boss",
          "정부",
          "government",
          "경제",
          "economics",
          "정치",
          "politics",
          "자유",
          "freedom",
          "사회",
          "society",
          "문화",
          "culture",
          "표",
          "ticket",
          "비행기표",
          "plane ticket",
          "감자튀김",
          "french fries",
          "숫자",
          "number, numeral",
          "비밀",
          "secret",
          "비밀 번호",
          "password",
          "그렇게",
          "so, in that way",
          "너무",
          "too (much), overly (adverb)",
          "때문에",
          "because of",
          "덕분에",
          "thanks to",
          "얼마입니까?",
          "How much is it?",
        ];
        const words = [
            ...lesson1to4, ...lesson5, ...lesson6,
            ...lesson7, ...lesson8, ...lesson9,
            ...lesson10, ...lesson11, ...lesson12
        ];
        const randWord = words[Math.floor(Math.random() * words.length)];
        document.getElementById("showWord").innerHTML = randWord;
    });
});
